### ISSUE TITLE
Some teacher images are not loading

### ISSUE THREAD

**Issue by ewoudenberg** [dharmaseed/dharmaseed-android#42]
E.g. Zohar Lavie (522), Yuka Nakamura (757), Willa Thaniya Reid (239), etc.

The teacher photo is available through e.g. 

http://dharmaseed.org/api/1/teachers/239/photo.png

However, it can be scaled by attaching a maxH and maxW parameter (one or both), e.g. fetching

http://dharmaseed.org/api/1/teachers/239/photo.png?maxW=350&maxH=350 

will cause a redirect to a generated or cached image here:

https://media.dharmaseed.org/uploads/photos/teacher_239_350_350.png

**Comment by jakewilson** [comment]
This might be fixed when #47 is fixed.

**Comment by jakewilson** [comment]
I believe this is now fixed. At least, all three teachers listed above have pictures on the latest version of master.
