### ISSUE TITLE
Starting the app seems unpredictable

### ISSUE THREAD

**Issue by jakewilson** [dharmaseed/dharmaseed-android#44]
Downloading the talks when opening the app for the first time seems unpredictable:

I fresh install the app, it downloads a single talk (or it only displays a single one), but navigating to the teachers page, it is filled with teachers. I clear data, re-run and it downloads what seems to be all the talks, but takes minutes and the "loading" circle animation doesn't go away.

This is vague, but the downloading of the dharma seed api on app start-up needs to be examined and improved.

**Comment by ewoudenberg** [comment]
Just beware that you are not being locked out of the site via stray references yielding 404s.
