### ISSUE TITLE
Add the repository pattern to the project

### ISSUE THREAD

**Issue by jakewilson** [dharmaseed/dharmaseed-android#46]
The [Repository Pattern](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/microservice-ddd-cqrs-patterns/infrastructure-persistence-layer-design#the-repository-pattern) separates the DB logic code from the 'client' (in this case, the presentation layer, or the activities). This is useful to allow for testing of DB methods, cleaning up the presentation layer, and removing duplication of code, among others. This became clear to me after trying to address issue #37 . With the current architecture, the best way to do this would be a query on line 283 here:

https://github.com/dharmaseed/dharmaseed-android/blob/cb642356e008fc5452f516ed94b1fbaaf29d06bf/app/src/main/java/org/dharmaseed/androidapp/NavigationActivity.java#L282-L289

And then circumventing a function call later down in the code. But this would only add to the vast amounts of querying done from the Activity and serve to make the logic less intuitive, less maintainable, and harder for a newcomer to understand. The goal would be to remove all queries from any Activity and to instead retrieve data via the respective `Repository`.

A good first step is to create a `TalkRepository` class for just the Talk entity, and then expanding as needed, only creating methods for accessing the DB _as needed_ and not creating a whole bunch of generic methods that aren't used.

This should be done _before_ #37.

**Comment by bb4242** [comment]
Done in #49
