### ISSUE TITLE
onUpgrade() should use `ALTER TABLE` instead of `DROP TABLE`

### ISSUE THREAD

**Issue by jakewilson** [dharmaseed/dharmaseed-android#56]
For example, when the `file_path` column was added to the `Talk` table, I added code in `onUpgrade()` to drop the table and re-create it:

https://github.com/dharmaseed/dharmaseed-android/blob/8979cc01b2b8d4070550a127cf2b235b828c7450/app/src/main/java/org/dharmaseed/android/DBManager.java#L252-L256

But we should strive to avoid dropping and re-adding any table because of the time taken to re-populate the entire thing (the `Talk` table takes somewhere around 10 minutes). Instead we should alter the table if we're just adding a column.

**Comment by ewoudenberg** [comment]
Has venue view is not a new column, it was there in the API all along.

**Comment by jakewilson** [comment]
Yes, but if I wanted just the "has_venue_view" columns of every venue, say, without all the other columns. Would that be possible to get from the API? Or if I wanted to get _just_ the rec_date of every talk, without any other columns.

**Comment by jakewilson** [comment]
Same as #62.
